export const LOAD_WEATHER_IN_CURRENT_LOCATION = 'LOAD_WEATHER_IN_CURRENT_LOCATION';
export const LOAD_WEATHER_IN_CURRENT_LOCATION_SUCCESS = 'LOAD_WEATHER_IN_CURRENT_LOCATION_SUCCESS';
export const LOAD_WEATHER_IN_CURRENT_LOCATION_FAILED = 'LOAD_WEATHER_IN_CURRENT_LOCATION_FAILED';

export const SET_CITY = 'SET_CITY';