export const LOAD_FAVORITES_DATA = 'LOAD_FAVORITES_DATA';
export const LOAD_FAVORITES_DATA_SUCCESS = 'LOAD_FAVORITES_DATA_SUCCESS';
export const LOAD_FAVORITES_DATA_FAILED = 'LOAD_FAVORITES_DATA_FAILED';

export const ADD_TO_FAVORITES_LIST = 'ADD_TO_FAVORITES_LIST';
export const REMOVE_FROM_FAVORITES_LIST = 'REMOVE_FROM_FAVORITES_LIST';